### PR TITLE
Revert "Task/migrate to wildfly 14"

### PR DESCRIPTION
**Pull request by stainii**
No. We've clearly agreed on not making any breaking changes for Wildfly 14 on dev until everything is properly tested by every party. This merge is against that agreement.

### CODE REVIEW

**Comment by ankovi** [comment]
This change is done as you can see in a library! And since even the artifactId of the library has changed then no-body would actually think of integrating the new version... so the risk of it being mistakenly integrated is practically 0!
That's why I did the merge! I'm not doing merges of App modules...

**Comment by stainii** [comment]
Still, code that is not compatible with Wildlfy 8 is on dev.
Without any communication at all: why it's done, why the artifact id has changed and why it's needed.

That in itself is a risk and not according to what we agreed on during the previous sprint review and on Slack.

**Comment by ankovi** [comment]
About the name change it was in place since we also changed the names of the plugins to make them more compatible with what they actually do.. so now the plugins are preceeded by flux- since they are flux plugins.. And this change was talked before since uvms-config is misleading and some of us got confused with a direct dependency to Config module which is not the case!
Again.. this was discussed before, just no body ever did it.. so now i did it!

**Comment by ankovi** [comment]
Anyway since I see that it really troubles you guys that's not a problem. We'll merge it when we merge all the other modules to dev.

**Pull request merged**
